### ISSUE TITLE
Suggestion: Make link(https://pub.dartlang.org/) configurable

### ISSUE THREAD

**Issue by Carl-Wen** [everettjf/vscode-pubspec-dependency-search#4]
Hello, can you please add options about config link in settings? I am in China, need search packages with [https://pub.flutter-io.cn/](https://pub.flutter-io.cn/) instead of [https://pub.dartlang.org/](https://pub.dartlang.org/).
Thank you!

**Comment by everettjf** [comment]
不好意思，我很久不学习和使用Flutter了。直接fork修改代码吧～

**Comment by Carl-Wen** [comment]
@everettjf 我提交了一个PR，你看一下。有可能的话希望merge后重新发布一下。谢谢。

**Comment by everettjf** [comment]
Done. Greate Thanks. @Carl-Wen
